version: '3.1'
services:
  db:
    container_name: moex_pg_local
    image: postgres:12.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_moex_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    network_mode: "host"
